# Generated by Django 5.1.4 on 2024-12-12 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('R', 'Romance'), ('A', 'Adventure'), ('F', 'Fantasy'), ('SF', 'Science Fiction'), ('H', 'Horror'), ('MY', 'Mystery'), ('TH', 'Thriller'), ('D', 'Drama'), ('C', 'Comedy'), ('SL', 'Slice of Life'), ('SH', 'Superhero'), ('MM', 'Mecha'), ('HIS', 'Historical'), ('MA', 'Martial Arts'), ('TR', 'Tragedy'), ('PAR', 'Paranormal'), ('P', 'Psychological'), ('SP', 'Sports'), ('W', 'Western'), ('DC', 'Dystopian')], default=0, max_length=25)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.story')),
            ],
        ),
    ]
