# Generated by Django 5.1.4 on 2024-12-12 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('A', 'Adventure'), ('C', 'Comedy'), ('D', 'Drama'), ('DC', 'Dystopian'), ('F', 'Fantasy'), ('H', 'Horror'), ('HIS', 'Historical'), ('MA', 'Martial Arts'), ('MM', 'Mecha'), ('MY', 'Mystery'), ('P', 'Psychological'), ('PAR', 'Paranormal'), ('R', 'Romance'), ('SF', 'Science Fiction'), ('SH', 'Superhero'), ('SL', 'Slice of Life'), ('SP', 'Sports'), ('TH', 'Thriller'), ('TR', 'Tragedy'), ('W', 'Western')], default=0, max_length=25),
        ),
    ]
